version: '3.8'
services:
  klee:
    container_name: klee_one_run_container
    build:
      context: ../../../../vulnerability_detection
      dockerfile: symb_exec/dockerfiles/klee_dockerfile
    restart: always
    env_file: .env
    environment:
      - PYTHONPATH=./
    volumes:
      - ../../../../vulnerability_detection:/home/klee/vulnerability_detection
    ulimits:
        stack:
            soft: -1
            hard: -1
    working_dir: /home/klee
    command: python3 vulnerability_detection/symb_exec/klee/app/klee_run.py
