version: '3.8'
services:
  triton:
    container_name: triton_container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    #    env_file: .env
    volumes:
        - ./utils:/Triton/build/utils
    working_dir: /Triton/build
    stdin_open: true
    tty: true
    #command: python3 utils/test.py
